<a href="https://colab.research.google.com/github/keerthibala07/Neural-Networks/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.15.0


In [ ]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
x_train

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.16096173, -0.22294326, -0.6177354 , -0.15476966, -0.6206345 ,
         0.4932183 , -0.06659187,  0.34255818, -0.1824156 ,  0.37902993]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.08633521, 0.08114649, 0.05467814, 0.08687147, 0.05451985,
        0.16607137, 0.09487948, 0.14284462, 0.08450272, 0.1481506 ]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

1.7953376

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 15s 7ms/step - loss: 0.2929 - accuracy: 0.9150
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1413 - accuracy: 0.9582
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1056 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0865 - accuracy: 0.9732
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0754 - accuracy: 0.9762


In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0771 - accuracy: 0.9759 - 618ms/epoch - 2ms/step


[0.07707854360342026, 0.9758999943733215]

# Datset 2 - fashion_mnist

In [ ]:
import tensorflow as tf

# Load Fashion-MNIST dataset
fashion_mnist = tf.keras.datasets.fashion_mnist
(x1_train, y1_train), (x1_test, y1_test) = fashion_mnist.load_data()

# Normalize pixel values to be between 0 and 1
x1_train, x1_test = x1_train / 255.0, x1_test / 255.0


4422102/4422102 [==============================] - 0s 0us/step


In [ ]:
x1_train

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [ ]:
model1 = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [ ]:
predictions1 = model1(x1_train[:1]).numpy()
predictions1

array([[ 0.48927602,  0.97533035,  1.4974356 , -0.6437154 , -0.9883305 ,
         0.8516182 ,  2.6645584 ,  0.21486619,  0.26273778, -2.213572  ]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions1).numpy()

array([[0.05623545, 0.09143256, 0.15411621, 0.01811166, 0.01283199,
        0.08079293, 0.49513465, 0.0427401 , 0.0448359 , 0.00376858]],
      dtype=float32)

In [ ]:
loss_fn1= tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn1(y1_train[:1], predictions1).numpy()

5.581056

In [ ]:
model1.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model1.fit(x1_train, y1_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2144 - accuracy: 0.9181
Epoch 2/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2138 - accuracy: 0.9200
Epoch 3/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2089 - accuracy: 0.9204
Epoch 4/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2097 - accuracy: 0.9199
Epoch 5/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2026 - accuracy: 0.9214
Epoch 6/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2035 - accuracy: 0.9220
Epoch 7/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2013 - accuracy: 0.9230
Epoch 8/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1993 - accuracy: 0.9243
Epoch 9/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1966 - accuracy: 0.9247
Epoch 10/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.195

In [ ]:
model1.evaluate(x1_test,  y1_test, verbose=2)

313/313 - 0s - loss: 0.3457 - accuracy: 0.8943 - 479ms/epoch - 2ms/step


[0.3457462191581726, 0.8942999839782715]

# Dataset 3

In [ ]:
cifar10 = tf.keras.datasets.cifar10
(x2_train, y2_train), (x2_test, y2_test) = cifar10.load_data()
x2_train, x2_test = x2_train / 255.0, x2_test / 255.0

In [ ]:
import tensorflow as tf

# Assuming x2_train has shape (num_samples, 32, 32, 3)
# Resize the images to (28, 28) using tf.image.resize
x2_train_resized = tf.image.resize(x2_train, (28, 28))

model2 = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28, 3)),  # Adjust the input shape
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

# Now, the following should work without an error
predictions2 = model2(x2_train_resized[:1]).numpy()
tf.nn.softmax(predictions2).numpy()

loss_fn2 = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)



In [ ]:
loss_fn2(y2_train[:1], predictions2).numpy()

2.1678839

In [ ]:
# Assuming x2_train has shape (num_samples, 32, 32, 3)
# Resize the images to (28, 28) using tf.image.resize
x2_train_resized = tf.image.resize(x2_train, (28, 28))

model2 = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28, 3)),  # Adjust the input shape
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

# Compile the model before fitting
model2.compile(optimizer='adam',
               loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
               metrics=['accuracy'])

# Now, you can fit the model
model2.fit(x2_train_resized, y2_train, epochs=10)


Epoch 1/10
1563/1563 [==============================] - 11s 7ms/step - loss: 2.0304 - accuracy: 0.2409
Epoch 2/10
1563/1563 [==============================] - 8s 5ms/step - loss: 1.9407 - accuracy: 0.2860
Epoch 3/10
1563/1563 [==============================] - 10s 6ms/step - loss: 1.9115 - accuracy: 0.2980
Epoch 4/10
1563/1563 [==============================] - 9s 6ms/step - loss: 1.8988 - accuracy: 0.3049
Epoch 5/10
1563/1563 [==============================] - 9s 6ms/step - loss: 1.8881 - accuracy: 0.3096
Epoch 6/10
1563/1563 [==============================] - 10s 7ms/step - loss: 1.8783 - accuracy: 0.3131
Epoch 7/10
1563/1563 [==============================] - 10s 7ms/step - loss: 1.8744 - accuracy: 0.3149
Epoch 8/10
1563/1563 [==============================] - 9s 6ms/step - loss: 1.8696 - accuracy: 0.3176
Epoch 9/10
1563/1563 [==============================] - 10s 6ms/step - loss: 1.8623 - accuracy: 0.3223
Epoch 10/10
1563/1563 [==============================] - 10s 6ms/step - loss:

In [ ]:
import tensorflow as tf

# Assuming x2_test has shape (num_samples, 32, 32, 3)
# Resize the test images to (28, 28) using tf.image.resize
x2_test_resized = tf.image.resize(x2_test, (28, 28))

# Assuming y2_test is the corresponding labels

# Compile the model before evaluation
model2.compile(optimizer='adam',
               loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
               metrics=['accuracy'])

# Now, you can evaluate the model
model2.evaluate(x2_test_resized, y2_test, verbose=2)


313/313 - 1s - loss: 1.7783 - accuracy: 0.3724 - 771ms/epoch - 2ms/step


[1.7782775163650513, 0.3723999857902527]